#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "test_plugin"
name = "test"
description.fr = "test_app"

version = "1.0"

maintainers = ["FrFredow"]



[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/FrFredow/yunohost_plugin_ynh/blob/master/yunohost_plugin_ynh.tar.gz"
        sha256 = "8e8fe3a113fe7ef1d4472691a29108dcfa8e3a4247b40c7e317cd415ca2b7655"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = true
    main.show_tile = true
    main.protected= true
    main.allowed = "admins"

    [resources.apt]
    packages = "php7.4-fpm, php8.0-fpm, php8.3-fpm"