id = "yunohost_plugin_ynh"
name = "YunoHost Plugin YNH"
description = "Un plugin YunoHost exemple"
version = "1.0.0"
maintainer = "FrFredow"
source = "https://github.com/FrFredow/yunohost_plugin_ynh"

# Dépendances (ajoutez celles qui sont nécessaires)
dependencies = []

# Definir les assets
assets = [
    { type = "main", url = "https://github.com/FrFredow/yunohost_plugin_ynh/blob/master/yunohost_plugin_ynh.tar.gz", sha256 = "5ea7e4c39f8e81f39f9ab43b6e1786ce2c175ae94f03b6c5a3e65f32d8b2a7fb" }
]




[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/exemple"



    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.auth_header = true
    main.show_tile = true
    main.protected= true
    main.allowed = "admins"

    [resources.apt]
    packages = "php7.4-fpm, php8.0-fpm, php8.3-fpm"