#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Installing My PHP Application..."

# Setup source
ynh_setup_source --dest_dir="$install_dir"

# Configure NGINX
ynh_config_add_nginx

# Configure PHP-FPM
ynh_config_add_phpfpm

# Setup service
ynh_config_add_systemd

# Start the service
ynh_systemctl --service="my_php_app" --action="start"

ynh_script_progression "Installation completed."
