#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Removing My PHP Application..."

# Stop service
ynh_systemctl --service="my_php_app" --action="stop"

# Remove configurations
ynh_config_remove_nginx
ynh_config_remove_phpfpm
ynh_config_remove_systemd

# Remove files
rm -rf "$install_dir"

ynh_script_progression "Removal completed."
