#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Upgrading My PHP Application..."

# Update source
ynh_setup_source --dest_dir="$install_dir"

# Restart service
ynh_systemctl --service="my_php_app" --action="restart"

ynh_script_progression "Upgrade completed."
